modLoader="javafml"
loaderVersion="[52,)"
issueTrackerURL=""
license = "MPL-2.0"

[[mods]]
modId = "examplemod"
version = "${version}"
displayName = "Example Mod"
authors = "Wagyourtail"
description = '''
    Mod for Block Game
'''

[[dependencies.examplemod]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"